### PR TITLE
Delete Messages Individually

### PR DESCRIPTION
**Pull request by thollingsheadesri**
Adds a trashcan icon for each message, allowing the message owner to delete unwanted messages from the client and database.

@gavinr @JevinAnderson @jwasil @BrianBunker Please review and approve changes to the chat app.

### CODE REVIEW

**Comment by jwasil** [comment]
@thollingsheadesri, visually it looks great to me, but I haven't had a chance to deploy it on my own and test it out at a deeper level.  Nice work!

**Comment by jwasil** [comment]
@thollingsheadesri building upon our delete icon size discussion for 18px, here is an example of what a possible hover state color would look like in both tagged and your own messages.  In this case I am using the pink color **#f22472** that appears in the left border of a tagged message in lets-chat.  Thoughts, anyone?  Extremely nitpicky, I know...
image

**Comment by hhaidar** [comment]
you'll need to check message ownership on the server too

**Comment by thollingsheadesri** [comment]
@jwasil The delete icon size has been set to 18px, and hover color to #f22472. Let me know what you think

**Comment by jwasil** [comment]
@thollingsheadesri thanks, looks good!  :shipit:

**Pull request merged**
